export const AGREGAR_PRODUCTO = 'AGREGAR_PRODUCTO'; 
export const AGREGAR_PRODUCTO_EXITO = 'AGREGAR_PRODUCTO_EXITO'; 
export const AGREGAR_PRODUCTO_ERROR = 'AGREGAR_PRODUCTO_ERROR'; 

export const EDITAR_PRODUCTO = 'EDITAR_PRODUCTO'; 
export const EDITAR_PRODUCTO_EXITO = 'EDITAR_PRODUCTO_EXITO'; 
export const EDITAR_PRODUCTO_ERROR = 'EDITAR_PRODUCTO_ERROR'; 

export const ELIMINAR_PRODUCTO = 'ELIMINAR_PRODUCTO'; 
export const ELIMINAR_PRODUCTO_EXITO = 'ELIMINAR_PRODUCTO_EXITO'; 
export const ELIMINAR_PRODUCTO_ERROR = 'ELIMINAR_PRODUCTO_ERROR'; 

export const LISTAR_PRODUCTO = 'LISTAR_PRODUCTO'; 
export const LISTAR_PRODUCTO_EXITO = 'LISTAR_PRODUCTO_EXITO'; 
export const LISTAR_PRODUCTO_ERROR = 'LISTAR_PRODUCTO_ERROR'; 