export const AGREGAR_PRODUCTO = 'AGREGAR_PRODUCTO'; 
export const AGREGAR_PRODUCTO_EXITO = 'AGREGAR_PRODUCTO_EXITO'; 
export const AGREGAR_PRODUCTO_ERROR = 'AGREGAR_PRODUCTO_ERROR'; 

export const COMENZAR_DESCARGA_PRODUCTO = 'COMENZAR_DESCARGA_PRODUCTO'; 
export const DESCARGA_PRODUCTO_EXITO = 'DESCARGA_PRODUCTO_EXITO'; 
export const DESCARGA_PRODUCTO_ERROR = 'DESCARGA_PRODUCTO_ERROR'; 

export const EDITAR_PRODUCTO = 'EDITAR_PRODUCTO'; 
export const COMENZAR_EDITAR_PRODUCTO = 'COMENZAR_EDITAR_PRODUCTO'; 
export const EDITAR_PRODUCTO_EXITO = 'EDITAR_PRODUCTO_EXITO'; 
export const EDITAR_PRODUCTO_ERROR = 'EDITAR_PRODUCTO_ERROR'; 

export const ELIMINAR_PRODUCTO = 'ELIMINAR_PRODUCTO'; 
export const ELIMINAR_PRODUCTO_EXITO = 'ELIMINAR_PRODUCTO_EXITO'; 
export const ELIMINAR_PRODUCTO_ERROR = 'ELIMINAR_PRODUCTO_ERROR'; 

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA'; 
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA'; 